import sys
import os
import json
import subprocess
from datetime import datetime

# Ensure workspace root is in path
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from scripts.scanner import run_full_scan

# CONFIGURATION
TARGET = "+601112827947"
STATE_FILE = os.path.join(os.path.dirname(__file__), "last_alert_state.json")
TAKER_THRESHOLD = 0.05 
PRICE_PROXIMITY = 0.001 
DECISION_ZONE = (1680.0, 1695.0)

def is_in_decision_zone(price):
    return DECISION_ZONE[0] <= price <= DECISION_ZONE[1]

def load_last_state():
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, 'r') as f:
                return json.load(f)
        except Exception:
            return None
    return None

def save_current_state(state):
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f)

def send_whatsapp(message, **kwargs): # Added **kwargs to accept gear_type
    # Add prefix to identify the sender of the alert
    prefix = "JIMI SMART ALERT: "
    # Add gear type to message if available
    gear_type = kwargs.get('gear_type')
    if gear_type:
        message = prefix + f"[{gear_type}] " + message
    else:
        message = prefix + message
    
    print(f"📤 Sending Alert to {TARGET}...")
    cmd = [
        "openclaw", "message", "send",
        "--channel", "whatsapp",
        "--target", TARGET,
        "--message", message
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(f"✅ Sent successfully: {result.stdout}")
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to send: {e.stderr}")

def check_triggers(current, last):
    if last is None:
        return True, "Initial Watchdog Activation"

    # 1. Verdict Change
    if current['verdict'] != last['verdict']:
        return True, f"Verdict Shift: {last['verdict']} ➔ {current['verdict']}"

    # 2. Taker Score Swing
    score_diff = abs(current['taker_score'] - last['taker_score'])
    if score_diff >= TAKER_THRESHOLD:
        return True, f"Conviction Swing: {last['taker_score']:.2f} ➔ {current['taker_score']:.2f}"

    # 3. Structural Break Flip
    if current['struct_break'] != last['struct_break']:
        return True, f"Structural State Changed: {last['struct_break']} ➔ {current['struct_break']}"

    # 4. Price Proximity to Magnets (Prevent Spamming)
    price = current['current_price']
    last_alerted_mag = last.get('last_alerted_magnet')
    
    for mag in current['magnets']:
        if abs(price - mag) / mag <= PRICE_PROXIMITY:
            # Only alert if it's a NEW magnet or we've moved away and come back
            if mag != last_alerted_mag:
                return True, f"Price Testing Critical Magnet: ${mag:.2f}"
    
    # If we are no longer near the previously alerted magnet, reset the alert state
    if last_alerted_mag:
        near_any = any(abs(price - mag) / mag <= PRICE_PROXIMITY for mag in current['magnets'])
        if not near_any:
            # We've moved away from all magnets, we can clear the last_alerted_magnet 
            # in the state update, but the trigger is False.
            pass

    return False, ""

def main():
    # Load last state to check price for adaptive polling
    last_state = load_last_state()
    
    # Run the JIMI scan first
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Checking for triggers...")
    results = run_full_scan()
    if not results:
        print("❌ Error: Could not get scan results.")
        return

    price = results.get('current_price', 0)
    
    # ADAPTIVE POLLING LOGIC
    if is_in_decision_zone(price):
        print(f"⚠️  PRICE IN DECISION ZONE (${price:.2f}). Increasing polling intensity.")
        # We can implement a sleep loop here or just rely on the parent task manager to re-trigger frequently
        # For this implementation, we proceed to run the check
    else:
        print(f"💤 Price (${price:.2f}) outside decision zone. Ambient mode.")

    # Extract key state
    current_state = {
        'verdict': results.get('verdict', 'N/A'),
        'taker_score': results.get('taker_score', 0.5),
        'struct_break': results.get('struct_break', False),
        'current_price': results.get('current_price', 0),
        'magnets': results.get('magnets', []),
        'last_alerted_magnet': None # Default
    }

    last_state = load_last_state()
    triggered, reason = check_triggers(current_state, last_state)

    # Always format the MSSP report generated by scanner.py
    mssp_report_text = results.get('mssp_report_text', "No MSSP Report generated.")
    gear_type = results.get('gear_type')

    # If there's a specific trigger, include it in the report summary
    if triggered:
        report_summary = f"🔔 TRIGGERED: {reason}\n" + mssp_report_text
    else:
        report_summary = mssp_report_text

    send_whatsapp(report_summary, gear_type=gear_type)
    save_current_state(current_state)
    
    # Only print "No significant change" if no message was actually sent (shouldn't happen with this logic)
    if not triggered and mssp_report_text == "No MSSP Report generated.":
        print("💤 No significant change. Skipping alert.")

if __name__ == "__main__":
    main()
